require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cargo/towns", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Cargo::Town. As you add validations to Cargo::Town, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cargo::Town.create! valid_attributes
      get cargo_towns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      town = Cargo::Town.create! valid_attributes
      get cargo_town_url(town)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cargo_town_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      town = Cargo::Town.create! valid_attributes
      get edit_cargo_town_url(town)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cargo::Town" do
        expect {
          post cargo_towns_url, params: { cargo_town: valid_attributes }
        }.to change(Cargo::Town, :count).by(1)
      end

      it "redirects to the created cargo_town" do
        post cargo_towns_url, params: { cargo_town: valid_attributes }
        expect(response).to redirect_to(cargo_town_url(Cargo::Town.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cargo::Town" do
        expect {
          post cargo_towns_url, params: { cargo_town: invalid_attributes }
        }.to change(Cargo::Town, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cargo_towns_url, params: { cargo_town: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cargo_town" do
        town = Cargo::Town.create! valid_attributes
        patch cargo_town_url(town), params: { cargo_town: new_attributes }
        town.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cargo_town" do
        town = Cargo::Town.create! valid_attributes
        patch cargo_town_url(town), params: { cargo_town: new_attributes }
        town.reload
        expect(response).to redirect_to(cargo_town_url(town))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        town = Cargo::Town.create! valid_attributes
        patch cargo_town_url(town), params: { cargo_town: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cargo_town" do
      town = Cargo::Town.create! valid_attributes
      expect {
        delete cargo_town_url(town)
      }.to change(Cargo::Town, :count).by(-1)
    end

    it "redirects to the cargo_towns list" do
      town = Cargo::Town.create! valid_attributes
      delete cargo_town_url(town)
      expect(response).to redirect_to(cargo_towns_url)
    end
  end
end
